### PR TITLE
add namespace to root element without prefix

### LINKED ISSUE #1: Shale cannot deal with default XML namespaces
Shale as it stands cannot deal with default namespaces, e.g. `<metanorma-collection xmlns="http://www.metanorma.org">`

If I specify

````
xml do
      root "metanorma-collection"
      namespace "http://metanorma.org", "m"
````

I get `<m:metanorma-collection>`, and namespacing for elements mapping to strings, but not elements generated through supplied methods.

If I specify

````
xml do
      root "metanorma-collection"
      namespace "http://metanorma.org", ""
````

I get `<: metanorma-collection>`

If I specify

````
xml do
      root "metanorma-collection"
      namespace "http://metanorma.org", nil
````

The namespace is completely ignored.

This is screwing me over in my effort to adopt Shale in Metanorma and refactor it, which is awful enough already without me having to deal with this as well.

### PR DESCRIPTION
**Pull request by HassanAkbar**
Allowing to add default namespaces

fixes #1

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@opoudjis / @andrew2net  I've added the option to add default namespaces. Is this what you are looking for?

**Review by andrew2net — APPROVED** [review]

**Review by ronaldtse — CHANGES_REQUESTED** [review]
Can we update the reader to indicate this new feature and explain the differences in output regarding “nil prefix”, “no prefix” and with prefix? Also I think we need an addition test for “nil prefix”

**Comment by HassanAkbar** [comment]
@ronaldtse Sure, I'll update the documentation and add the required test cases.
But what do you really mean by `update the reader to indicate this new feature`?

**Comment by ronaldtse** [comment]
Sorry I meant README.

**Comment by HassanAkbar** [comment]
@ronaldtse Got it. I'll update the readme.

**Review by opoudjis — APPROVED** [review]
Looks fine to me, though I would have preferred to see a roundtrip test:

````
require 'shale'
class Person  < ::Shale::Mapper
  require 'shale/adapter/nokogiri'
  ::Shale.xml_adapter = ::Shale::Adapter::Nokogiri

  attribute :output1, ::Shale::Type::String
  attribute :output2, ::Shale::Type::String
  xml do
    root 'collection'
    namespace 'http://metanorma.org', nil
    map_attribute 'output1', to: :output1
    map_element 'output2', to: :output2
  end
end

person = Person.from_xml(<<~DATA)
  <collection xmlns="http://metanorma.org" output1='A'>
    <output2>John</output2>
    </collection>
DATA

pp person.to_xml
````

**Comment by ronaldtse** [comment]
Let's merge this first because we don't want to wait to use this.

**Pull request merged**
